<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Scrutor" Version="7.0.0" />
        <PackageReference Include="Spectre.Console" Version="0.56.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RestaurantReservation.Domain\RestaurantReservation.Domain.csproj" />
      <ProjectReference Include="..\RestaurantReservation.Infrastructure\RestaurantReservation.Infrastructure.csproj" />
    </ItemGroup>

</Project>
